#!/usr/bin/env php
<?php
// application.php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Account\AccountCommand;

$application = new Application();

// ... register commands
$application->add(new AccountCommand());

$application->run();