#!/usr/bin/env php
<?php
// application.php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Account\Commands\AccountInfoCommand;
use Account\Commands\AccountOpenCommand;
use Account\Commands\AccountCloseCommand;
use Account\Commands\AccountDepositCommand;
use Account\Commands\AccountWithdrawalCommand;
use Account\Commands\AccountListTransactionCommand;
use Account\Commands\AccountBalanceCommand;

$application = new Application();

// ... register commands
$application->add(new AccountInfoCommand());
$application->add(new AccountOpenCommand());
$application->add(new AccountCloseCommand());
$application->add(new AccountDepositCommand());
$application->add(new AccountWithdrawalCommand());
$application->add(new AccountListTransactionCommand());
$application->add(new AccountBalanceCommand());

$application->run();